package com.example.shortener.service;

import com.example.shortener.domain.ShortUrl;
import com.example.shortener.domain.ShortenerExceptions.InvalidRequestException;
import com.example.shortener.domain.ShortenerExceptions.LinkGoneException;
import com.example.shortener.support.InMemoryShortUrlStore;
import com.example.shortener.support.MutableClock;
import org.junit.jupiter.api.Test;

import java.time.Duration;
import java.time.Instant;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

/** Generated by the SDLC orchestrator for the max-clicks feature (AC traceability in the test plan). */
class MaxClicksLimitTest {

    private final ShortUrlService service = new ShortUrlService(new InMemoryShortUrlStore(),
            new UrlValidator(Set.of(), ""), new CodeGenerator(7),
            new MutableClock(Instant.parse("2026-01-01T00:00:00Z")),
            new ShortUrlService.Policy(null, Duration.ofDays(30), 5, Set.of(), "salt"));

    private final ShortUrlService.ClickContext ctx = new ShortUrlService.ClickContext(null, "JUnit", "203.0.113.1");

    @Test
    void linkStopsRedirectingAfterMaxClicks() {
        ShortUrl link = service.create(new ShortUrlService.CreateCommand("https://example.com", null, null, 2L));

        assertEquals("https://example.com", service.resolve(link.getCode(), ctx));
        assertEquals("https://example.com", service.resolve(link.getCode(), ctx));
        assertThrows(LinkGoneException.class, () -> service.resolve(link.getCode(), ctx));
    }

    @Test
    void linksWithoutBudgetBehaveAsBefore() {
        ShortUrl link = service.create(new ShortUrlService.CreateCommand("https://example.com", null, null));

        assertNull(link.getMaxClicks());
        for (int i = 0; i < 10; i++) {
            assertEquals("https://example.com", service.resolve(link.getCode(), ctx));
        }
    }

    @Test
    void nonPositiveBudgetIsRejected() {
        assertThrows(InvalidRequestException.class,
                () -> service.create(new ShortUrlService.CreateCommand("https://example.com", null, null, 0L)));
    }
}
