CREATE TABLE short_url (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(32)   NOT NULL,
    target_url   VARCHAR(2048) NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at   TIMESTAMP WITH TIME ZONE,
    click_count  BIGINT        NOT NULL DEFAULT 0,
    active       BOOLEAN       NOT NULL DEFAULT TRUE,
    version      BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT uk_short_url_code UNIQUE (code)
);

CREATE TABLE click_event (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(32)  NOT NULL,
    occurred_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    referrer     VARCHAR(512),
    user_agent   VARCHAR(512),
    client_hash  VARCHAR(64)
);

CREATE INDEX ix_click_event_code_time ON click_event (code, occurred_at);
